- better performance logging with DEBUG log level - fixed bug in spf in case of splitted TXT record in DNS - disabled spf internal DNS cache (not thread safe, out of control) - DB_ENGINE constant to specify mysql database type - ppolicy can listen on more ports for conncetion from postfix   with different configuration - added GeoIP/Country module - fixed bug in greylist expiration - updated dynamic patterns - updated and patched pyspf from http://sourceforge.net/projects/pymilter - changed log dir to /var/log/ppolicy - added support to reload ppolicy.conf on SIGHUP   (right now only simple changes in check method are safe) - added P0f module - added Whois module (dummy skeleton)

diff --git a/ppolicy.init b/ppolicy.init
--- a/ppolicy.init
+++ b/ppolicy.init
@@ -6,7 +6,7 @@
 # description: Start-up script for the Twisted service ppolicy.tap
 # processname: ppolicy
 # config: /etc/postfix/ppolicy.conf
-# pidfile: /var/spool/ppolicy/ppolicy.pid
+# pidfile: /var/log/ppolicy/ppolicy.pid
 
 # Source function library.
 . /etc/rc.d/init.d/functions
@@ -15,10 +15,10 @@
 PPOLICY_ACCOUNT="nobody"
 SYSCONFIG="/etc/sysconfig/ppolicy"
 
-pidfile=/var/spool/ppolicy/ppolicy.pid
-rundir=/var/spool/ppolicy
+pidfile=/var/log/ppolicy/ppolicy.pid
+rundir=/var/log/ppolicy
 file=/usr/sbin/ppolicy.tap
-logfile=/var/spool/ppolicy/ppolicy.log
+logfile=/var/log/ppolicy/ppolicy.log
 twistd=/usr/bin/twistd
 
 prog="ppolicy"
@@ -40,6 +40,11 @@ fi
 if [ ! -d "${rundir}" ]; then
     echo "$0: Aborting, run directory $rundir doesn't exist."
     exit 1
+fi
+if [ `id -u $PPOLICY_ACCOUNT` != `stat --format=%u ${rundir}` ]; then
+    echo "$0: Aborting, run directory $rundir owner differs from ppolicy account."
+    exit 1
+    #chown -R $PPOLICY_ACCOUNT ${rundir}
 fi
 
 start() {
